version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      # git-auto-commit-action v6は壊れているようなので、一旦無視
      - dependency-name: "stefanzweifel/git-auto-commit-action"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
  - package-ecosystem: "npm"
    directory: "/"
    groups:
      all:
        patterns:
          - "*"
    ignore:
      # Node.jsのメジャーバージョンは変更しない
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "daily"
    cooldown:
      default-days: 7
